SET DATA_ROOT="D:/CVPR21_freshmeat/7_11_localpos_nocct/box/"
SET MODEL_ROOT="D:/CVPR21_models/7_11_localpos_nocct/models/"
SET MODEL_FILE_NAME="model_state_1750000.pkl"

SET SAMPLE_VIEW_NUM=24
SET ROTATE_VIEW_NUM=1
SET MEASUREMENT_LEN=4
SET DIFT_CODE_LEN=3
SET VIEW_CODE_LEN=128

python infer_pos.py %DATA_ROOT% %MODEL_ROOT% %MODEL_FILE_NAME% %SAMPLE_VIEW_NUM% %ROTATE_VIEW_NUM% %MEASUREMENT_LEN% %DIFT_CODE_LEN% %VIEW_CODE_LEN%
python visualize_nn_pos.py %DATA_ROOT% %ROTATE_VIEW_NUM% %DIFT_CODE_LEN%