@echo off

SET DATA_ROOT="G:/CVPR21_freshmeat/11_7_mainresults/iccv_cat/"
SET MODEL_ROOT="G:/CVPR21_models/iccv_test/models/"
SET MODEL_FILE_NAME="model_state_1080000.pkl"

SET SAMPLE_VIEW_NUM=24
SET ROTATE_VIEW_NUM=24
SET MEASUREMENT_LEN=8
SET DIFT_CODE_LEN_G=64
SET DIFT_CODE_LEN_M=64
SET COLMAP_CODE_LEN=4

python infer_dift_codes.py %DATA_ROOT% %MODEL_ROOT% %MODEL_FILE_NAME% %SAMPLE_VIEW_NUM% %ROTATE_VIEW_NUM% %MEASUREMENT_LEN% %DIFT_CODE_LEN_G% %DIFT_CODE_LEN_M%

SET /A DIFT_CODE_LEN=(%DIFT_CODE_LEN_G%+%DIFT_CODE_LEN_M%)*3
python compact_dift_codes.py %DATA_ROOT% %ROTATE_VIEW_NUM% %DIFT_CODE_LEN% %COLMAP_CODE_LEN% --imgheight 3000 --imgwidth 4096

@echo on